// export const BIO_TAGS = [
//   { value: "O", label: "O" },
//   { value: "B-per", label: "B-PER" },
//   { value: "I-per", label: "I-PER" },
//   { value: "B-org", label: "B-ORG" },
//   { value: "I-org", label: "I-ORG" },
//   { value: "B-geo", label: "B-GEO" },
//   { value: "I-geo", label: "I-GEO" },
//   { value: "B-gpe", label: "B-GPE" },
//   { value: "I-gpe", label: "I-GPE" },
//   { value: "B-tim", label: "B-TIM" },
//   { value: "I-tim", label: "I-TIM" },
//   { value: "B-art", label: "B-ART" },
//   { value: "I-art", label: "I-ART" },
//   { value: "B-eve", label: "B-EVE" },
//   { value: "I-eve", label: "I-EVE" },
//   { value: "B-nat", label: "B-NAT" },
//   { value: "I-nat", label: "I-NAT" },
// ] as const;

export const BIO_TAGS = [
  { value: "O", label: "Не сущность" },
  { value: "B-per", label: "Человек" },
  { value: "B-org", label: "Организация" },
  { value: "B-geo", label: "Географическое место" },
  { value: "B-gpe", label: "Страна/город (полит.)" },
  { value: "B-tim", label: "Дата/время" },
  { value: "B-art", label: "Артефакт" },
  { value: "B-eve", label: "Событие" },
  { value: "B-nat", label: "Природное явление" },
  { value: "I-per", label: "Продолжение человека" },
  { value: "I-org", label: "Продолжение организации" },
  { value: "I-geo", label: "Продолжение geo" },
  { value: "I-gpe", label: "Продолжение gpe" },
  { value: "I-tim", label: "Продолжение времени" },
  { value: "I-art", label: "Продолжение артефакта" },
  { value: "I-eve", label: "Продолжение события" },
  { value: "I-nat", label: "Продолжение natural" },
] as const;

export type BioTag = (typeof BIO_TAGS)[number]["value"];
